#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## Customize to your needs...

# Disable ZSH Autocorrect completely
unsetopt CORRECT

# Update PATH Variable
export PATH=$PATH:~/bin:~/.minions:"/Applications/Sublime Text.app/Contents/SharedSupport/bin:"

##
# Aliases
##

alias rm='echo "rm is disabled, use trash or /bin/rm instead."'
alias ts='trash $@'


# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# iTerm2 Shell integration
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
