#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## Customize to your needs...

# Disable rm
alias rm='echo "rm is disabled, use trash or /bin/rm instead."'

# Disable ZSH Autocorrect completely
unsetopt CORRECT

# Update PATH Variable
export PATH=$PATH:~/bin:~/.minions:"/Applications/Sublime Text.app/Contents/SharedSupport/bin"

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export NVM_DIR="/Users/saneef/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

